/**
 * Standard IB Financial Statement Templates
 * 
 * These templates provide the standard structure for each financial statement.
 * Users can customize by adding/removing rows or breaking down consolidated items.
 */

import type { Row } from "@/types/finance";

/**
 * Standard Income Statement Template (IB-grade)
 */
export function createIncomeStatementTemplate(): Row[] {
  return [
    {
      id: "rev",
      label: "Revenue",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      sectionOwner: "revenue",
      isOperating: true,
      isTemplateRow: true,
    },
    {
      id: "cogs",
      label: "Cost of Goods Sold (COGS)",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      sectionOwner: "cogs",
      isOperating: true,
      isTemplateRow: true,
    },
    {
      id: "gross_profit",
      label: "Gross Profit",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [],
      isTemplateRow: true,
    },
    {
      id: "gross_margin",
      label: "Gross Margin %",
      kind: "calc",
      valueType: "percent",
      values: {},
      children: [],
      isTemplateRow: true,
    },
    {
      id: "operating_expenses",
      label: "Operating Expenses",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [
        {
          id: "sga",
          label: "Selling, General & Administrative (SG&A)",
          kind: "input",
          valueType: "currency",
          values: {},
          children: [],
          sectionOwner: "sga",
          isOperating: true,
          isTemplateRow: true,
        },
        {
          id: "rd",
          label: "Research & Development (R&D)",
          kind: "input",
          valueType: "currency",
          values: {},
          children: [],
          sectionOwner: "rd",
          isOperating: true,
          isTemplateRow: true,
        },
        {
          id: "other_opex",
          label: "Other Operating Expenses",
          kind: "input",
          valueType: "currency",
          values: {},
          children: [],
          sectionOwner: "other_operating",
          isOperating: true,
          isTemplateRow: true,
        },
        {
          id: "danda",
          label: "Depreciation & Amortization (D&A)",
          kind: "input",
          valueType: "currency",
          values: {},
          children: [],
          sectionOwner: "other_operating",
          isOperating: true,
          isTemplateRow: true,
        },
      ],
      sectionOwner: "operating_expenses",
      isTemplateRow: true,
    },
    {
      id: "ebit",
      label: "EBIT (Operating Income)",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [],
      isTemplateRow: true,
    },
    {
      id: "ebit_margin",
      label: "EBIT Margin %",
      kind: "calc",
      valueType: "percent",
      values: {},
      children: [],
      isTemplateRow: true,
    },
    {
      id: "interest_expense",
      label: "Interest Expense",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      sectionOwner: "non_operating",
      isOperating: false,
      isTemplateRow: true,
    },
    {
      id: "interest_income",
      label: "Interest Income",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      sectionOwner: "non_operating",
      isOperating: false,
      isTemplateRow: true,
    },
    {
      id: "other_income",
      label: "Other Income / (Expense), net",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      sectionOwner: "non_operating",
      isOperating: false,
      isTemplateRow: true,
    },
    {
      id: "ebt",
      label: "EBT (Earnings Before Tax)",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [],
      isTemplateRow: true,
    },
    {
      id: "tax",
      label: "Income Tax Expense",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      sectionOwner: "tax",
      isOperating: false,
      isTemplateRow: true,
    },
    {
      id: "net_income",
      label: "Net Income",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [],
      isTemplateRow: true,
    },
    {
      id: "net_income_margin",
      label: "Net Income Margin %",
      kind: "calc",
      valueType: "percent",
      values: {},
      children: [],
      isTemplateRow: true,
    },
  ];
}

/**
 * Standard Balance Sheet Template (IB-grade)
 * Core rows so schedules (WC, Capex, Intangibles, etc.) can identify which items to use.
 * Total/subtotal row IDs and order must not change; users can add/remove non-total rows.
 */
export function createBalanceSheetTemplate(): Row[] {
  return [
    // CURRENT ASSETS
    {
      id: "cash",
      label: "Cash",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "non_cash",
    },
    {
      id: "ar",
      label: "Accounts Receivable",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "working_capital",
    },
    {
      id: "inventory",
      label: "Inventory",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "working_capital",
    },
    {
      id: "other_ca",
      label: "Other Current Assets",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "working_capital",
    },
    {
      id: "total_current_assets",
      label: "Total Current Assets",
      kind: "subtotal",
      valueType: "currency",
      values: {},
      children: [],
    },
    // FIXED ASSETS
    {
      id: "ppe",
      label: "Property, Plant & Equipment (PP&E)",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "investing",
    },
    {
      id: "intangible_assets",
      label: "Intangible Assets",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "investing",
    },
    {
      id: "goodwill",
      label: "Goodwill",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "non_cash",
    },
    {
      id: "other_assets",
      label: "Other Long-Term Assets",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "non_cash",
    },
    {
      id: "total_fixed_assets",
      label: "Total Fixed Assets",
      kind: "subtotal",
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "total_assets",
      label: "Total Assets",
      kind: "total",
      valueType: "currency",
      values: {},
      children: [],
    },
    // CURRENT LIABILITIES
    {
      id: "ap",
      label: "Accounts Payable",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "working_capital",
    },
    {
      id: "accrued_liabilities",
      label: "Accrued Liabilities",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "working_capital",
    },
    {
      id: "deferred_revenue",
      label: "Deferred Revenue",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "working_capital",
    },
    {
      id: "st_debt",
      label: "Short-Term Debt",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "financing",
    },
    {
      id: "other_cl",
      label: "Other Current Liabilities",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "working_capital",
    },
    {
      id: "total_current_liabilities",
      label: "Total Current Liabilities",
      kind: "subtotal",
      valueType: "currency",
      values: {},
      children: [],
    },
    // NON-CURRENT LIABILITIES
    {
      id: "lt_debt",
      label: "Long-Term Debt",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "financing",
    },
    {
      id: "other_liab",
      label: "Other Liabilities",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "non_cash",
    },
    {
      id: "total_non_current_liabilities",
      label: "Total Non-Current Liabilities",
      kind: "subtotal",
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "total_liabilities",
      label: "Total Liabilities",
      kind: "total",
      valueType: "currency",
      values: {},
      children: [],
    },
    // EQUITY (core items)
    {
      id: "common_stock",
      label: "Common Stock",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "financing",
    },
    {
      id: "apic",
      label: "Additional Paid-in Capital",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "financing",
    },
    {
      id: "treasury_stock",
      label: "Treasury Stock",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "financing",
    },
    {
      id: "retained_earnings",
      label: "Retained Earnings",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "non_cash",
    },
    {
      id: "other_equity",
      label: "Other Equity",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
      cashFlowBehavior: "non_cash",
    },
    {
      id: "total_equity",
      label: "Total Equity",
      kind: "total",
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "total_liab_and_equity",
      label: "Total Liabilities & Equity",
      kind: "total",
      valueType: "currency",
      values: {},
      children: [],
    },
  ];
}

/**
 * Standard Cash Flow Statement Template (IB-grade)
 */
export function createCashFlowTemplate(): Row[] {
  return [
    // Operating Activities
    {
      id: "net_income",
      label: "Net Income",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "danda",
      label: "Depreciation & Amortization",
      kind: "input", // Manual input in CFO
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "sbc",
      label: "Stock-Based Compensation",
      kind: "calc", // Calculated from SBC breakdowns
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "wc_change",
      label: "Change in Working Capital",
      kind: "input", // Input for first historical year, calculated for subsequent years
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "other_operating",
      label: "Other Operating Activities",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "operating_cf",
      label: "Cash from Operating Activities",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [],
    },
    // Investing Activities
    {
      id: "capex",
      label: "Capital Expenditures (CapEx)",
      kind: "input",
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "investing_cf",
      label: "Cash from Investing Activities",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [],
    },
    // Financing Activities
    // No default items - user chooses from suggestions or adds manually
    {
      id: "financing_cf",
      label: "Cash from Financing Activities",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [],
    },
    {
      id: "net_change_cash",
      label: "Net Change in Cash",
      kind: "calc",
      valueType: "currency",
      values: {},
      children: [],
    },
  ];
}
